# Generated by Django 4.2.6 on 2024-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/default_profile.png",
                upload_to="profile_images/",
            ),
        ),
    ]
