# Generated by Django 4.2.6 on 2024-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="New User", max_length=50),
        ),
    ]
