# Generated by Django 4.2.16 on 2024-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/default_profile.png",
                upload_to="profile_images/",
            ),
        ),
    ]
