# Generated by Django 4.2.16 on 2024-12-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
