# Generated by Django 4.2.16 on 2024-12-21 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_notification_event_type_notification_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
