# Generated by Django 4.2.16 on 2025-01-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
