# Generated by Django 4.2.16 on 2025-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.URLField(
                blank=True,
                default="https://res.cloudinary.com/dkmwoidaa/image/upload/v1736835004/profile_images/kaft7arwqbkxzdw2qerj.png",
                max_length=500,
                null=True,
            ),
        ),
    ]
