services:
  backend:
    build:
      context: ./backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - .env
    depends_on:
      - redis
    user: "1000:1000"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - .env
    user: "1000:1000"
  
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    platform: linux/amd64  # プラットフォームを指定
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app:delegated  # 必要な部分だけマウント
      - node_modules:/app/node_modules  # node_modulesはDockerのボリュームで管理
    env_file:
      - ./frontend/app/.env

volumes:
  node_modules:  # フロントエンド用のnode_modulesボリュームを定義
