services:
  - type: web
    name: my-backend-staging
    env: python
    region: singapore
    plan: free
    branch: staging
    healthCheckPath: /health/
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p 10000 backend.asgi:application"
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERUSER_NAME
        value: "admin"
      - key: SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: SUPERUSER_PASSWORD
        value: "password"
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: ALLOWED_HOSTS
        value: "my-backend-staging.onrender.com"
      - key: CLOUDINARY_URL
        value: "${CLOUDINARY_URL}"
      - key: RENDER_ENV
        value: "production"
      - key: ASGI_APPLICATION
        value: "backend.asgi.application"

# Frontend の設定
  - type: web
    name: my-frontend-staging
    env: node
    region: singapore
    plan: free
    branch: staging
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s dist -l 3000"
    rootDir: frontend/app  # フロントエンドのソースディレクトリ
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://my-backend-staging.onrender.com"
      - key: VITE_WEBSOCKET_URL
        value: "wss://my-backend-staging.onrender.com"