services:
  - type: web
    name: my-backend-staging
    env: python
    region: singapore
    plan: free
    branch: staging
    healthCheckPath: /health/
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:10000 --log-file -"
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERUSER_NAME
        value: "admin"
      - key: SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: SUPERUSER_PASSWORD
        value: "password"
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,backend,backend:8000"
      - key: CLOUDINARY_URL
        value: "${CLOUDINARY_URL}"
