services:
  - type: web
    name: my-backend
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /health/
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:10000 --log-file -"
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERUSER_NAME
        value: "admin"
      - key: SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: SUPERUSER_PASSWORD
        value: "password"