"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# プロジェクトのベースディレクトリ
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gbf-7o_d=76+g0^x4u1^ku+4g&&yu1!k*ff7mpt$ms(d^(yi!x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'accounts',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_yasg',
    'courses',
    'channels',
    'django_celery_results',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'

if os.getenv('RENDER_ENV') == 'production':  # 本番環境 (Render)
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_ROOT = None  # Cloudinaryに保存するためローカルのMEDIA_ROOTは不要
else:  # ローカル環境
    MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# CORS
CORS_ALLOW_ALL_ORIGINS = True  # 一時的に全てのオリジンを許可
CORS_ALLOW_HEADERS = [
    'content-type',
    'x-requested-with',
    'authorization',
    'accept',
    'origin',
    'user-agent',
]
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'OPTIONS',
    'PUT',
    'DELETE',
    'PATCH',
]

# 必要ならばデバッグ用のロガーを追加
import logging

logging.basicConfig(level=logging.DEBUG)

# Channels settings (WebSocket)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv('REDIS_URL')],  # Render環境変数からRedisのURLを取得
        },
    },
}

# Celery settings
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')  # 本番環境のRedis URL
CELERY_RESULT_BACKEND = 'django-db'  # 本番環境はDBを使用
CELERY_ACCEPT_CONTENT = ['json']  # 受け入れるコンテンツタイプ
CELERY_TASK_SERIALIZER = 'json'  # タスクシリアライザ
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # 再試行を有効化


# # Channels settings (WebSocket)
# if os.getenv('RENDER_ENV') == 'production':  # 本番環境
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
#             "CONFIG": {
#                 "hosts": [os.getenv('REDIS_URL')],  # Render環境変数からRedisのURLを取得
#             },
#         },
#     }
# else:  # ローカル開発環境
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
#             "CONFIG": {
#                 "hosts": [("localhost", 6379)],  # ローカルのRedisインスタンスを使用
#             },
#         },
#     }

# # Celery settings
# if os.getenv('RENDER_ENV') == 'production':  # 本番環境
#     CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')  # 本番環境のRedis URL
#     CELERY_RESULT_BACKEND = 'django-db'  # 本番環境はDBを使用
# else:  # ローカル環境
#     CELERY_BROKER_URL = 'redis://localhost:6379/0'  # ローカルRedisの設定
#     CELERY_RESULT_BACKEND = 'django-db'  # ローカルでもDBを使用

# CELERY_ACCEPT_CONTENT = ['json']  # 受け入れるコンテンツタイプ
# CELERY_TASK_SERIALIZER = 'json'  # タスクシリアライザ
# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # 再試行を有効化

# テスト環境用設定
if os.environ.get('TESTING', 'False') == 'True':
    CELERY_TASK_ALWAYS_EAGER = True  # 非同期タスクを同期的に実行
    CELERY_TASK_EAGER_PROPAGATES = True  # エラーを即座に伝播
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

SUPERUSER_NAME = os.getenv('SUPERUSER_NAME')
SUPERUSER_EMAIL = os.getenv('SUPERUSER_EMAIL')
SUPERUSER_PASSWORD = os.getenv('SUPERUSER_PASSWORD')