# Generated by Django 4.2.6 on 2024-11-03 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_file_created_by_module_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="order",
        ),
    ]
