# Generated by Django 4.2.6 on 2024-11-09 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_remove_module_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="title",
        ),
    ]
