# Generated by Django 4.2.16 on 2024-12-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_enrollment_moduleprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Please enter a rating between 1 and 5 stars.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Provide detailed feedback on the course (optional).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        help_text="Feedback can only be submitted once per enrollment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="courses.enrollment",
                    ),
                ),
            ],
        ),
    ]
